# Generated by Django 4.1.7 on 2023-03-08 09:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_groupquestion_time_askquestionattended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 8, 15, 20, 16, 763709), null=True),
        ),
    ]
