# Generated by Django 4.1.7 on 2023-03-08 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_askquestion_id_alter_groupquestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 8, 15, 21, 1, 596555), null=True),
        ),
    ]
