# Generated by Django 4.1.7 on 2023-07-09 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_alter_askquestion_id'),
        ('user', '0001_initial'),
        ('question', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('visited', models.BooleanField(blank=True, default=False, null=True)),
                ('source', models.CharField(default='ik', max_length=100)),
                ('revealed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='user.profile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AskedLike',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('visited', models.BooleanField(default=False)),
                ('source', models.CharField(default='user', max_length=100)),
                ('revealed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.askquestion')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuserask', to='user.profile')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touserask', to='user.profile')),
            ],
        ),
    ]
