# Generated by Django 4.1.7 on 2023-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_askedlike_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
