# Generated by Django 4.1.7 on 2023-03-07 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_alter_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 7, 13, 46, 32, 503478), null=True),
        ),
    ]
