# Generated by Django 4.1.7 on 2023-03-08 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_alter_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 8, 15, 21, 46, 690389), null=True),
        ),
    ]
