# Generated by Django 4.1.7 on 2023-07-09 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('total_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('mode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
