# Generated by Django 4.1.7 on 2023-03-04 10:21

import datetime
from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_time', models.DateField(blank=True, null=True)),
                ('paid', models.CharField(default='False', max_length=200)),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 15, 51, 32, 114303), null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('otp', models.CharField(default=user.models.key_generator, max_length=6, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
