# Generated by Django 4.1.7 on 2023-03-04 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 22, 31, 22, 628419), null=True),
        ),
    ]
