# Generated by Django 4.1.7 on 2023-03-08 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 8, 15, 33, 48, 750750), null=True),
        ),
    ]
